# Generated by Django 5.0.3 on 2024-03-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('DO', 'Doing'), ('DN', 'Done'), ('CA', 'Canceled')], default='Not Started', max_length=2)),
                ('difficult_level', models.CharField(choices=[('VE', 'Very Easy'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('VH', 'Very Hard')], max_length=2)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.post')),
            ],
        ),
    ]
