# Generated by Django 5.0.3 on 2024-03-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='difficult_level',
            new_name='c',
        ),
    ]
