# Generated by Django 5.0.3 on 2024-03-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_rename_difficult_level_task_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='c',
            new_name='difficult_level',
        ),
    ]
